### ISSUE TITLE
多个JSON对象（或struct）的encode、decode的实现

### ISSUE THREAD

**Issue by kgbook** [jobs-github/slothjson#1]
根据design.md和structs.md介绍，可以实现多个JSON对象的encode、decode。

sample.json
```json
{
	"structs":
	[
		{
			"type" : "json_data_t",
			"members" : 
			[
				["bool", "error", "true"],
				["string", "message", "404 not found"],
				["int16_t", "code", "0"],
				["double", "nonce", "0.6268985954069382"],
				["int64_t", "timestamp", "1532269760476"]
			]
		},
		{
			"type" : "signature_data_t",
			"members" :
			[
				["string", "signature"]
			]
		},
		{
			"type" : "root_t",
			"members" :
			[
				["json_data_t", "jsonObj"],
				["signature_data_t", "signatureObj"]
			]
		}
	]
}
```
`slothjson.py  -f sample.json` 生成sample.cpp 、sample.h  文件，测试代码：
```cpp
//
// Created by kang on 2018/7/22.
//
#include "sample.h"
#include <iostream>

using namespace std;

int main(int argc, char **argv){
    std::string jsonString("{\"json\":\"{\\\"error\\\":true,\\\"message\\\":\\\"404 not found\\\",\\\"code\\\":0,\\\"nonce\\\":\\\"0.6268985954069382\\\",\\\"timestamp\\\":1532269760476}\",\"signature\":\"bC06V8aGU1WLPgAUOjI0kJaLqGgKLhkOUBY9NWm86QS2wkHIcb76Y26+gh5aDTRjF9XYR470esF1Whj4i1v6nb5nCRfMCGF6nh8k1j+gZtkipVeDKYgrncTbKApVymMXwvHBRYiR/bwpVpONA7m6M1f9tZegegmaDz3+s4jfudo=\"}");
    slothjson::root_t rootObj;
    bool ret;

    ret = slothjson::decode(jsonString, rootObj);
    if (!ret){
        cout <<__func__ <<":"<<__LINE__<<", decode() failed！"<<endl;
        return -1;
    }

    return 0;
}
```

调试信息：
```shell
Breakpoint 1, main (argc=1, argv=0x7fffffffe398) at /home/kgbook/json/test.cpp:15
15	    if (!ret){
(gdb) p rootObj
$1 = {jsonObj = {error = true, message = "404 not found", code = 0, nonce = 0.62689859540693815, timestamp = 1532269760476, __skip_error = false, __skip_message = false, __skip_code = false, 
    __skip_nonce = false, __skip_timestamp = false, __json_has_error = false, __json_has_message = false, __json_has_code = false, __json_has_nonce = false, __json_has_timestamp = false}, 
  signatureObj = {signature = "", __skip_signature = false, __json_has_signature = false}, __skip_jsonObj = false, __skip_signatureObj = false, __json_has_jsonObj = false, 
  __json_has_signatureObj = false}
```
解析出来`signatureObj`有问题，signature为空。

**Comment by kgbook** [comment]
为进一步验证，修改如下：
测试代码
```cpp
int main(int argc, char **argv){
    std::string jsonString("{\"json\":\"{\\\"error\\\":true,\\\"message\\\":\\\"404 not found\\\",\\\"code\\\":0,\\\"nonce\\\":\\\"0.6268985954069382\\\",\\\"timestamp\\\":1532269760476}\",\"signature\":\"bC06V8aGU1WLPgAUOjI0kJaLqGgKLhkOUBY9NWm86QS2wkHIcb76Y26+gh5aDTRjF9XYR470esF1Whj4i1v6nb5nCRfMCGF6nh8k1j+gZtkipVeDKYgrncTbKApVymMXwvHBRYiR/bwpVpONA7m6M1f9tZegegmaDz3+s4jfudo=\"}");
    slothjson::root_t rootObj;
    slothjson::json_data_t jsonObj;
    slothjson::signature_data_t signatureObj;

    bool ret;

    ret = slothjson::decode(jsonString, rootObj);
    if (!ret){
        cout <<__func__ <<":"<<__LINE__<<", decode() failed！"<<endl;
        return -1;
    }

    ret = slothjson::decode(jsonString, jsonObj);
    if (!ret){
        cout <<__func__ <<":"<<__LINE__<<", decode() failed！"<<endl;
        return -1;
    }

    ret = slothjson::decode(jsonString, signatureObj);
    if (!ret){
        cout <<__func__ <<":"<<__LINE__<<", decode() failed！"<<endl;
        return -1;
    }

    return 0;
}
```
运行结果
```shell
(gdb) r
Starting program: /home/kgbook/json/build/json 

Breakpoint 1, main (argc=1, argv=0x7fffffffe398) at /home/kgbook/json/test.cpp:30
30	    if (!ret){
(gdb) p rootObj
$1 = {jsonObj = {error = true, message = "404 not found", code = 0, nonce = 0.62689859540693815, timestamp = 1532269760476, __skip_error = false, __skip_message = false, __skip_code = false, 
    __skip_nonce = false, __skip_timestamp = false, __json_has_error = false, __json_has_message = false, __json_has_code = false, __json_has_nonce = false, __json_has_timestamp = false}, 
  signatureObj = {signature = "", __skip_signature = false, __json_has_signature = false}, __skip_jsonObj = false, __skip_signatureObj = false, __json_has_jsonObj = false, 
  __json_has_signatureObj = false}
(gdb) p jsonObj
$2 = {error = true, message = "404 not found", code = 0, nonce = 0.62689859540693815, timestamp = 1532269760476, __skip_error = false, __skip_message = false, __skip_code = false, __skip_nonce = false, 
  __skip_timestamp = false, __json_has_error = false, __json_has_message = false, __json_has_code = false, __json_has_nonce = false, __json_has_timestamp = false}
(gdb) p signatureObj
$3 = {signature = "bC06V8aGU1WLPgAUOjI0kJaLqGgKLhkOUBY9NWm86QS2wkHIcb76Y26+gh5aDTRjF9XYR470esF1Whj4i1v6nb5nCRfMCGF6nh8k1j+gZtkipVeDKYgrncTbKApVymMXwvHBRYiR/bwpVpONA7m6M1f9tZegegmaDz3+s4jfudo=", 
  __skip_signature = false, __json_has_signature = true}
```
测试结果：
- 未配置`__skip_signatureObj`, 默认`__skip_signature = false`；单个JSON对象解析，`signatureObj`非空，解析OK；多个JSON对象一起解析，`signatureObj`为空，解析失败。
- 多个JSON对象decode时候`__json_has_signatureObj`为`false`, 而单个解析时候为`true`。

多个JSON对象decode存在问题。

**Comment by jobs-github** [comment]
输入的 json 串有问题，请用如下代码测试：

    void test()
    {
        std::string json_val = "\
        {\
            \"jsonObj\": {\
                \"error\": true,\
                \"message\": \"404 not found\",\
                \"code\": 0,\
                \"nonce\": 0.6268985954069382,\
                \"timestamp\": 1532269760476\
            },\
            \"signatureObj\": {\
                \"signature\": \"bC06V8aGU1WLPgAUOjI0kJaLqGgKLhkOUBY9NWm86QS2wkHIcb76Y26+gh5aDTRjF9XYR470esF1Whj4i1v6nb5nCRfMCGF6nh8k1j+gZtkipVeDKYgrncTbKApVymMXwvHBRYiR/bwpVpONA7m6M1f9tZegegmaDz3+s4jfudo=\"\
            }\
        }";

        slothjson::root_t out;
        if (!slothjson::decode(json_val, out))
        {
            printf("decode error\n");
            return;
        }

        slothjson::root_t in;

        in.jsonObj.error = true;
        in.jsonObj.message = "404 not found";
        in.jsonObj.code = 0;
        in.jsonObj.nonce = 0.6268985954069382;
        in.jsonObj.timestamp = 1532269760476;
        in.signatureObj.signature = "bC06V8aGU1WLPgAUOjI0kJaLqGgKLhkOUBY9NWm86QS2wkHIcb76Y26+gh5aDTRjF9XYR470esF1Whj4i1v6nb5nCRfMCGF6nh8k1j+gZtkipVeDKYgrncTbKApVymMXwvHBRYiR/bwpVpONA7m6M1f9tZegegmaDz3+s4jfudo=";

        if (in == out)
        {
            printf("ok\n");
        }
        else
        {
            printf("fail\n");
        }
    }

可以使用如下代码来查看正确的json的字符串格式：

    slothjson::root_t in;

    in.jsonObj.error = true;
    in.jsonObj.message = "404 not found";
    in.jsonObj.code = 0;
    in.jsonObj.nonce = 0.6268985954069382;
    in.jsonObj.timestamp = 1532269760476;
    in.signatureObj.signature = "bC06V8aGU1WLPgAUOjI0kJaLqGgKLhkOUBY9NWm86QS2wkHIcb76Y26+gh5aDTRjF9XYR470esF1Whj4i1v6nb5nCRfMCGF6nh8k1j+gZtkipVeDKYgrncTbKApVymMXwvHBRYiR/bwpVpONA7m6M1f9tZegegmaDz3+s4jfudo=";

    slothjson::dump <true> (in, "test.json");

**Comment by kgbook** [comment]
根据你的提示，确实发现问题，主要：
1.  respond拷贝到CLion，双引号`\"`转义可能存在问题，会自动插入三个斜杠，多了两斜杠；
2. 数据描述文件有些问题，部分数据类型，比如小数部分我们我们使用的`string`，而我错误地使用`double`来解析。
3. respond的JSON格式与dump出的数据格式有些不一致。

新的sample.json为：
```json
{
	"structs":
	[
		{
			"type" : "json_data_t",
			"members" :
			[
				["bool", "error", "true"],
				["string", "message", "404 not found"],
				["int16_t", "code", "0"],
				["string", "nonce", "0.6268985954069382"],
				["int64_t", "timestamp", "1532269760476"]
			]
		},
		{
			"type" : "root_t",
			"members" :
			[
				["json_data_t", "json"],
				["string", "signature"]
			]
		}
	]
}
```

对于问题3，

我们的json数据格式：
```json
"{\"json\":\"{\"error\":true,\"message\":\"404 not found\",\"code\":0,\"nonce\":\"0.5245370697198866\",\"timestamp\":1532319323203}\",\"signature\":\"vuLFaphbAn98Y77kQbmmavbfTT7sxzHv/CuBoacSpsStxRXYLOWp/dAq2SLd1bO3vTYOQK5YtYkbplggozZpSIbqJpxCZvkHysA+N/i+LXAiSkj2fuWWRqpBkAmzLsO6Fnyb1wcUKlSM0JdIZzoMzidH5ZQHEk4JEKgUDfkxmhk=\"}"
```
dump输出的json：
```json
"{\"json\":{\"error\":true,\"message\":\"404 not found\",\"code\":0,\"nonce\":\"0.5245370697198866\",\"timestamp\":1532319323203},\"signature\":\"vuLFaphbAn98Y77kQbmmavbfTT7sxzHv/CuBoacSpsStxRXYLOWp/dAq2SLd1bO3vTYOQK5YtYkbplggozZpSIbqJpxCZvkHysA+N/i+LXAiSkj2fuWWRqpBkAmzLsO6Fnyb1wcUKlSM0JdIZzoMzidH5ZQHEk4JEKgUDfkxmhk=\"}"
```
问题3会导致signature解析失败，数据空。

两者的差异：
对于`root_t`中的`json`对象，`{`和`}`之间的数据通过双引号`\"`包起来了，dump出来的数据没有。

dump出的JSON数据是标准格式吗？

我们的JSON数据都是这格式：
```json
{
  "json": "....",
  "signature": "..."
}
```

前端给予我的反馈是json格式改不了。

目前的思路是字符串查找，删除或插入双引号。
如果在slothjson中支持这格式，我需要做哪方面改动？感谢

**Comment by jobs-github** [comment]
slothjson底层基于[rapidjson](https://github.com/Tencent/rapidjson)，是标准格式。

建议发一个最原始的例子过来，不带任何转义的json字符串。以便于理清对象的类型和层次关系。

**Comment by kgbook** [comment]
@jobs-github 
url：http://recognition.bi.tuputech.com/v3/recognition
可以用这链接返回的json数据测试。

**Comment by kgbook** [comment]
我现在主要解决问题3，其它问题都是小问题。

**Comment by jobs-github** [comment]
根据接口返回的json数据， **`root_t` 里面的 `json` 的类型为 `string`** ：

    {
        "structs":
        [
            ......
            {
                "type" : "root_t",
                "members" :
                [
                    ["string", "json"],
                    ......
                ]
            }
        ]
    }

数据的解码需要进行两次decode，写法如下：

    std::string json_val = "{\"json\":\"{\"error\":true,\"message\":\"404 not found\",\"code\":0,\"nonce\":\"0.5245370697198866\",\"timestamp\":1532319323203}\",\"signature\":\"vuLFaphbAn98Y77kQbmmavbfTT7sxzHv/CuBoacSpsStxRXYLOWp/dAq2SLd1bO3vTYOQK5YtYkbplggozZpSIbqJpxCZvkHysA+N/i+LXAiSkj2fuWWRqpBkAmzLsO6Fnyb1wcUKlSM0JdIZzoMzidH5ZQHEk4JEKgUDfkxmhk=\"}";

    slothjson::root_t root;
    slothjson::decode(json_val, root);

    slothjson::json_data_t json_data;
    slothjson::decode(root.json, json_data);

**Comment by kgbook** [comment]
考虑多次decode；感谢～

**Comment by kgbook** [comment]
多次decode不可行。

解析Document类失败，ParseErrorCode :` kParseErrorObjectMissCommaOrCurlyBracket`。
假设json数据为
```json
"{\"json\":\"{\"message\":\"404 not found\"}\",\"signature\":\"2nAD1k7cqW\"}"
```
RapidJSON不会把`json`的值` \"{\"message\":\"404 not found\"}\"`当作`string`处理，会被作为对象继续展开解析.
```shell
rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>::ParseStream<0u, rapidjson::UTF8<char>, rapidjson::GenericStringStream<rapidjson::UTF8<char> > > (this=0x7fffffffe080, is=...) at /home/kgbook/json/include/rapidjson/document.h:2260
2260	        if (parseResult_) {
(gdb) p is
$4 = (rapidjson::GenericStringStream<rapidjson::UTF8<char> > &) @0x7fffffffdff0: {src_ = 0x624c2b "message\":\"404 not found\"}\",\"signature\":\"2nAD1k7cqW\"}", 
  head_ = 0x624c20 "{\"json\":\"{\"message\":\"404 not found\"}\",\"signature\":\"2nAD1k7cqW\"}"}
(gdb) p parseResult_
$5 = {code_ = rapidjson::kParseErrorObjectMissCommaOrCurlyBracket, offset_ = 11}
```
[RapidJSON Tutorial](https://miloyip.github.io/rapidjson/md_doc_tutorial.html)

Milo Yip 的回复也表明RapdiJSON不支持只做第一层键值对的解析。

**Comment by jobs-github** [comment]
rapidjson不支持你提供的这种json格式的解析，可用如下代码测试：

    std::string json_val = "{\"json\":\"{\"error\":true,\"message\":\"404 not found\",\"code\":0,\"nonce\":\"0.5245370697198866\",\"timestamp\":1532319323203}\",\"signature\":\"vuLFaphbAn98Y77kQbmmavbfTT7sxzHv/CuBoacSpsStxRXYLOWp/dAq2SLd1bO3vTYOQK5YtYkbplggozZpSIbqJpxCZvkHysA+N/i+LXAiSkj2fuWWRqpBkAmzLsO6Fnyb1wcUKlSM0JdIZzoMzidH5ZQHEk4JEKgUDfkxmhk=\"}";

    rapidjson::Document doc;
    doc.Parse(json_val.c_str());
    rapidjson::Value value;
    if (!slothjson::decode_document(doc, value))
    {
        return;
    }
    if (value.IsNull())
    {
        printf("is null");
    }

`slothjson` 底层使用 `rapidjson` 进行json的解析，**如果 `rapidjson` 解析不了，`slothjson` 也无能为力**。

所以，建议使用以下方式解决你的问题：

* 换其他开源的 json parser 试试看。可以尝试 [jsoncpp](https://github.com/open-source-parsers/jsoncpp) 。当然，这个没有现成的工具，你需要自己定义对象模型，原理是类似的。但我需要提示风险，`rapidjson` 的性能极高，更换其他的解析库会降低性能。这个需要你自己权衡。
* 让前端增加新的接口，举例： `http://recognition.bi.tuputech.com/v4/recognition`，然后返回的 `json` 格式让 `rapidjson` 能够解析。参考我的第一段回复。这个方法的成本要小很多。

如果以上的建议都不能帮你解决问题，你只能自己写 `json parser` 了（当然，这个代价和复杂度都是最高的，你的项目的时间成本不一定支持你这么做）。**毕竟 `slothjson` 本身就不是一个 json parser**，它是基于现有的 json parser 做的自动化工具。

**Comment by kgbook** [comment]
CLion 自动插入三个斜杠+双引号的做法是正确的，而我人为去除并只保留一个斜杠是错误的。
嵌套双引号，上述所述场景需要转义两次，`\\\"`转义一次为`\"`，转义两次为`"`，所以我这保留一个斜杠的做法会导致`decode`失败。

另外，C++ 11 支持Raw String Literals。

example：
```cpp
string in = "{\"json\":\"{\\\"error\\\":true,\\\"message\\\":\\\"404 not found\\\",\\\"code\\\":0,\\\"nonce\\\":\\\"0.8054632351656703\\\",\\\"timestamp\\\":1532525070907}\",\"signature\":\"Q5s1tDJVXWcNXp\"}";
```
```cpp
string in = R"({
                        "json":"{\"error\":true,\"message\":\"404 not found\",\"code\":0,\"nonce\":\"0.8054632351656703\",\"timestamp\":1532525070907}",
                        "signature":"Q5s1tDJVXWcNXp"
                    })";
```
这两中写法都是OK的，json已解析OK；感谢。
