### ISSUE TITLE
Is supported nested object ?

### ISSUE THREAD

**Issue by zghnr1993** [jobs-github/slothjson#4]
hello , 
你这个支持复杂的数据结构吗？ 比如一个Nested objects  . 如果支持的话， 有没有example啊？

**Comment by jobs-github** [comment]
你好，支持的，参见：https://github.com/jobs-github/slothjson/blob/master/doc/en/schema.md

**Comment by zghnr1993** [comment]
好的，谢谢！ 
我想问下，你这个考虑支持从api 直接生成code吗？ 或者更通用的json  object 去生成呢？ 现在感觉你这个有点定制的意思，还是需要人工去定制json的。

**Comment by jobs-github** [comment]
你好，你所说的方案，我理解是go那种在结构体后面加标签的做法？例如：

        type Response struct {
		ResultCode string         `json:"result_code"`
		DebugMsg   string         `json:"debug_msg"`
		Data       AccountPayload `json:"data"`
	}
如果我理解的不对，欢迎用具体例子说明你的想法。
如果我理解的对，我需要做如下说明：
这种方法有两个问题，第一，实现和具体语言绑定，不具备通用性，属于专用解决方案，和 slothjson 所使用的[DSL](https://github.com/jobs-github/yas)的设计相悖；第二，在C++里可用宏实现此需求，但相应的代价是[极大的提高编译成本](https://github.com/jobs-github/slothjson/blob/master/doc/zh/FAQ.md)。
综上所述，暂不考虑在 slothjson 里支持类似的做法，**这个项目不是这个定位**。
BTW: 如果你确实有兴趣了解如何用宏实现这种解法，可以私下沟通。

**Comment by zghnr1993** [comment]
做成go那样的tag的方式，C++确实不好做，毕竟没有reflect 。然后，我本以为你是否有想 openapi-specification https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#parameter-object 这种标准的方向拓展的。 看到你说的是基于YAS（Yet Another Schema，我不了解这个），你就当我没说 。哈哈！
